### ISSUE TITLE
Increase timeout for periodic jobs

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#462] opened 2019-03-27 09:37 UTC
Increase timeout for periodic jobs as far as job on 2a failed on that: https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/150/console

**Comment by ibuziuk** [comment] 2019-03-27 11:46
root cause is https://status.starter.openshift.com/incidents/3tb5kx8149s3
if it fails from time to time no action item is required IMO

**Comment by ibuziuk** [comment] 2019-03-28 12:12
could we consider closing it in favour of https://github.com/openshiftio/openshift.io/issues/4769

**Comment by Katka92** [comment] 2019-03-28 20:20
Agreed, closing.

**Closed** 2019-03-28 20:20 UTC
